### ISSUE TITLE
Unable to make it work

### ISSUE THREAD

**Issue by Archetipo95** [storybook-vue/nuxt#5]
Hi! I'm having troubles testing this project. The minimal reproduction is to init a new Nuxt project with the command `npx nuxi@latest init PROJECT_NAME` and then inside the root of the project I tried the command suggested in the README `npx storybook@latest init`
But it's not working, it runs, it asks me for the builder used in the project (I selected vite) and then it tell me "Storybook was successfully installed in your project! 🎉" but that's not true! My package.json is untouched and ofc the command `yarn storybook` fails.

I tried with node v16 and v18. Currently Im using `yarn`

**Comment by LucaMargadant** [comment]
I got it running in a nuxt project which uses yarn and Node 18.

To me your issue sounds more related to install the storybook itself than this package.

You need to use storybook for vue. I followed back then this guide here [https://storybook.js.org/docs/vue/get-started/install](https://storybook.js.org/docs/vue/get-started/install).

To be honest i had to manually add the storybook command into my package.json like that:

`"storybook": "yarn sb dev -p 6006",`

After that i installed the @storybook-vue/nuxt package with `yarn add -D @storybook-vue/nuxt` and added it to the framework in main.ts of storybook:

`  framework: {
    name: "@storybook-vue/nuxt",
    options: {},
  },`

If it's still not working, there is also a working Demo Repo you can clone and try out on your machine. Maybe it helps to spot out differences to your setup and figure out more informations why it's not running.

**Comment by Archetipo95** [comment]
So this is the correct command to run `npx storybook@latest init --type vue3`

**Comment by chakAs3** [comment]
> So this is the correct command to run `npx storybook@latest init --type vue3`
> 
> Btw `yarn` is giving me a lot of problems, I recommend mend to use `pnpm`

you are. total right.  I really recommend pnpm as yarn is hell. 
 
the storybook init command for nuxt. is ready but not yet. merged to main so you solution is quite good for now all what you have to do after is change your  _`.storybook/main.js`_

**Comment by chakAs3** [comment]
**GENERAL RECOMMENDATION**:  if you start any new project that does not have any Yarn legacy,  please use **PNPM**. it will change your life and avoid you Yarn depression

**Comment by DanHulton** [comment]
So, I'm stuck in the boat where I'm still using Yarn, because Yarn has the ability to install multiple versions of a package for different architectures - this means it can install both a copy for my local Mac arch and the docker image arch at once, which is really convenient - one `yarn install` means it works locally and in Docker.  PNPM doesn't offer this yet, and from looking at the comment thread about it, may not ever.

What is the general issue that's preventing yarn from working here?  Like, this is the first-ever package I've come across that doesn't work because you're using a different major, well-supported package manager, so I'm just really confused about what could be the problem.

**Comment by chakAs3** [comment]
@DanHulton  please start by opening more specific issue regarding yarn, cause this is closed and clearly too vague

**Comment by DanHulton** [comment]
@chakAs3 Ah, sorry, my bad on two counts:

1) I meant to make the comment on this issue: https://github.com/storybook-vue/storybook-nuxt/issues/39
2) I didn't want to open an actual issue, as you've already expressed a lack of interest in fixing yarn bugs, I was just hoping that the OP of that issue remembered what the problem was, and that I could use that to look further into it.  I figured if I _was_ able to make it work, I could just open a PR, so you didn't actually have to spend any time working on a yarn issue.  But I should have been explicit about that when I was commenting.
