### ISSUE TITLE
Question: Build and Deploy the storybook

### ISSUE THREAD

**Issue by LucaMargadant** [storybook-vue/nuxt#6]
Hi there, 

Yesterday i run into a problem while deploying the storybook to Vercel where the build command was never ending.

After that i tried it out locally with the demo repo mentioned in the Readme. It was the same behavior. It starts building storybook, is writing everything into the `storybook-static/` Folder until this message appears: `ℹ page reload storybook-static/iframe.html`. From there the build gets stuck. No errors shown.

Could it be that the app needs to run in dev mode on a Node server? Or do you have a recommendation for the deployment process?

Thanks in advance!

**Comment by chakAs3** [comment]
Hi @LucaMargadant, I encountered the same issue while creating a sandbox and using the deployment script, I guess i have to check out this part, as it is handled by Nuxt ( Nitro ), need all static-assets generated by storybook this one I haven't tested yet.

**Comment by chakAs3** [comment]
@lateek35 can first use the new package as i have done many changes maybe this issue occurring

**Comment by LucaMargadant** [comment]
@lateek35 The thing is that the "static" build still needs a node environment as it builds and holds a Nuxt application behind. If you deploy it to a Node server or similar you can run it with the dev command.

In the middle of the week (maybe wednesday) I guess I get a full day to test all the new things of you @chakAs3 released on the next tag of the new monorepo. Also there is still an issue with Vercel where Vercel drops the files of the first build and replaces it with the second build of the dev command. I have some ideas for this issue i want to try out and would like to investigate after checking the new versions of @chakAs3.

**Comment by lateek35** [comment]
@LucaMargadant  Thanks for this clarifications, I'll probably have to rethink my deployment system as the current dedicated hosting for our storybook doesn't support node. Given that my nuxt application doesn't use srr (yet) and the folder is called `storybook-static` it led me to believe that the build didn't need a node environment. 

So if I understand correctly, we can't really deploy using the `storybook build` that generate the `storybook-static` folder, but instead we should use `storybook dev` ? But I believe I might have misunderstood something on this matter, otherwise you probably wouldn't have taken the time to resolve the issue with the `ℹ page reload storybook-static/iframe.html` previously occurring on that `storybook build` command if the latter was ultimately not usable for deployement.

**Comment by chakAs3** [comment]
@LucaMargadant you can start testing using monorepo, with the new pkg name. @storybook-nuxt/framework

just run `pnpm dev`  there is a playground

**Comment by moifort** [comment]
> https://www.npmjs.com/package/@storybook-nuxt/framework

@LucaMargadant I am not sure to understand, if you use NuxtJs with no SSR, your build should work in static right? Because when I try to run the build I have the same error as you. I am trying to understand why we have this error `Failed to resolve module specifier "vue"` when we run the static folder. Maybe we are missing adding the Vue library @chakAs3, do you have any idea?
